# Generated by Django 5.2.8 on 2025-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_signup_completed_to_useroidc"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitebranding",
            name="theme_preset_dark",
            field=models.CharField(
                blank=True,
                default="business",
                help_text="DaisyUI preset theme for dark mode (e.g., 'business', 'dark', 'synthwave')",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="theme_preset_light",
            field=models.CharField(
                blank=True,
                default="wireframe",
                help_text="DaisyUI preset theme for light mode (e.g., 'wireframe', 'cupcake', 'light')",
                max_length=64,
            ),
        ),
    ]
