# Generated by Django 5.2.8 on 2025-11-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_sitebranding_theme_preset_dark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitebranding",
            name="theme_preset_dark",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DaisyUI preset theme for dark mode (e.g., 'business', 'dark', 'synthwave'). Defaults to BRAND_THEME_PRESET_DARK setting.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="sitebranding",
            name="theme_preset_light",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DaisyUI preset theme for light mode (e.g., 'nord', 'cupcake', 'light'). Defaults to BRAND_THEME_PRESET_LIGHT setting.",
                max_length=64,
            ),
        ),
    ]
