# Generated by Django 5.2.8 on 2025-11-17 17:41

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0024_dataset_last_scraped_dataset_nhs_dd_published_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConversationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_history",
                    models.JSONField(
                        default=list,
                        help_text="List of {role, content, timestamp} message dictionaries",
                    ),
                ),
                (
                    "current_markdown",
                    models.TextField(blank=True, help_text="Latest generated markdown"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one active session per user-survey pair",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_conversations",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Conversation Session",
                "verbose_name_plural": "LLM Conversation Sessions",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["survey", "user", "-updated_at"],
                        name="surveys_llm_survey__bc9cca_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-updated_at"],
                        name="surveys_llm_is_acti_9bdec5_idx",
                    ),
                ],
            },
        ),
    ]
